### ISSUE TITLE
Add schema and utility code to request/return dataset access info

### ISSUE THREAD

**Issue by ryanrdoherty** [VEuPathDB/EdaCommon#7]
```
{
 /studyId/: {
    studyMetadata: boolean // study metadata
    subsetting: boolean       // count, distribution
    visualizations: boolean  // all viz plugins
    resultsFirstPage: boolean // offset:0, numRecords: <=20
    resultsAll: boolean           // any other tabular response
  }
}
```

TODO: write wrapper service around the download site

https://docs.google.com/document/d/1avpDOz81X2Q8BMg1NwXpix6lco6WfSGQTTUtdTzmIdI/edit#

**Comment by danicahelb** [comment]
Discussed with Ryan via Slack

We are supplementing one of the endpoints with more exact permissions (calculated on the backend) so the client does not need to calculate them.  Things like: if a study is "protected" and user is a guest then they can view study metadata but can not access visualizations.  

This is per the access table here:
https://docs.google.com/document/d/1avpDOz81X2Q8BMg1NwXpix6lco6WfSGQTTUtdTzmIdI/edit#heading=h.r60j2i44kggd

**Comment by danicahelb** [comment]
Wrapper service around the download site is covered in https://github.com/VEuPathDB/EdaNewIssues/issues/69

**Comment by ryanrdoherty** [comment]
This was completed as described a while back and is functional and well tested.

**Comment by nkittur-uga** [comment]
Works as expected. As guest- In protected study (e.g. GEMS1), downloads are blocked. Other tabs like browse, viz are available. In public ICEMR study downloads are allowed.
